<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork865-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [1]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
                                              0.0/6.0 MB ? eta -:--:--
                                              0.0/6.0 MB 1.3 MB/s eta 0:00:05
                                              0.1/6.0 MB 1.4 MB/s eta 0:00:05
     -------                                  1.0/6.0 MB 8.3 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 8.3 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 8.3 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 8.3 MB/s eta 0:00:01
     --------------                           2.1/6.0 MB 7.4 MB/s eta 0:00:01
     --------------                           2.1/6.0 MB 7.4 MB/s eta 0:00:01
     ---------------------                    3.1/6.0 MB 7.7 MB/s eta 0:00:01
     ---------------------                    3.1/6.0 MB 7.7 MB/s eta 0:00:01
     ----------------------------             4.2/6.0 MB 8.9 MB/s eta 0:00:01
     ----------------------------             4.2/6.0 MB 8.9 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     -----------------------------------      5.2/6.0 MB 9.1 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py): started
  Building wheel for sqlalchemy (setup.py): finished with status 'done'
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp310-cp310-win_amd64.whl size=1163608 sha256=1c8c5387575d797d9f2b62bda4132d801e65a0112960276fec5b899126d048f4
  Stored in directory: c:\users\edwar\appdata\local\pip\cache\wheels\8b\6d\9c\e1793e5a2d85b89b8c362a4f0e3def54b786bcd14923b9ff00
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.39
    Uninstalling SQLAlchemy-1.4.39:
      Successfully uninstalled SQLAlchemy-1.4.39
Successfully installed sqlalchemy-1.3.9

WARNING: Ignoring invalid distribution -atplotlib (c:\users\edwar\anaconda3\envs\coursera-env\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\edwar\anaconda3\envs\coursera-env\lib\site-packages)

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
%load_ext sql

In [3]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [4]:
#!pip install -q pandas==1.1.5

In [5]:
%sql sqlite:///my_data1.db

'Connected: @my_data1.db'

In [6]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

999

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [203]:
%sql select "Launch_Site" from SPACEXTBL group by "Launch_Site"

 * sqlite:///my_data1.db
Done.

[(None,),
 ('CCAFS LC-40',),
 ('CCAFS SLC-40',),
 ('KSC LC-39A',),
 ('VAFB SLC-4E',)]


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [69]:
%sql select * from SPACEXTBL \
    where "Launch_Site" like "CCA%" \
    limit 5;

 * sqlite:///my_data1.db
Done.

[('06/04/2010', '18:45:00', 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0.0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)'),
 ('12/08/2010', '15:43:00', 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0.0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)'),
 ('22/05/2012', '7:44:00', 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525.0, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt'),
 ('10/08/2012', '0:35:00', 'F9 v1.0  B0006', 'CCAFS LC-40', 'SpaceX CRS-1', 500.0, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt'),
 ('03/01/2013', '15:10:00', 'F9 v1.0  B0007', 'CCAFS LC-40', 'SpaceX CRS-2', 677.0, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'No attempt')]

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [55]:
%sql select sum("PAYLOAD_MASS__KG_") as "Total payload mass carried by boosters launched by NASA (CRS)"\
    from SPACEXTBL \
    where Customer = "NASA (CRS)";

 * sqlite:///my_data1.db
Done.

[(45596.0,)]

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [54]:
%sql select avg("PAYLOAD_MASS__KG_") as "Average payload mass carried by F9 v1.1 booster"\
    from SPACEXTBL \
    where "Booster_Version" like "F9 v1.1%";

 * sqlite:///my_data1.db
Done.

[(2534.6666666666665,)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

Can't seem to correctly use min function as SQLite does not recognise the Date column as in date type, instead in TEXT type. To change this, I first renamed "Date" to "Launch_Date" to prevent any confusion when later using the date() function. Then I reformatted from 'dd/mm/YYYY' to 'YYYY-mm-dd' so that the date() function would accept it. Now I can find the earliest date correctly.

In [104]:
# Debugging.
# SQL is picking the smallest DAY, i.e. 01 instead of the earliest actual DATE
# First rename "Date" as can cause issues

%sql alter table SPACEXTBL \
    rename column Date to "Launch_Date";

 * sqlite:///my_data1.db
(sqlite3.OperationalError) no such column: "Date"
[SQL: alter table SPACEXTBL      rename column Date to "Launch_Date";]
(Background on this error at: http://sqlalche.me/e/e3q8)

In [105]:
# Debugging
# Check data type of "Launch_Date"

%sql pragma table_info(SPACEXTBL)

 * sqlite:///my_data1.db
Done.

[(0, 'Launch_Date', 'TEXT', 0, None, 0),
 (1, 'Time (UTC)', 'TEXT', 0, None, 0),
 (2, 'Booster_Version', 'TEXT', 0, None, 0),
 (3, 'Launch_Site', 'TEXT', 0, None, 0),
 (4, 'Payload', 'TEXT', 0, None, 0),
 (5, 'PAYLOAD_MASS__KG_', 'REAL', 0, None, 0),
 (6, 'Orbit', 'TEXT', 0, None, 0),
 (7, 'Customer', 'TEXT', 0, None, 0),
 (8, 'Mission_Outcome', 'TEXT', 0, None, 0),
 (9, 'Landing_Outcome', 'TEXT', 0, None, 0)]

In [107]:
# Debugging
# Changing "Launch_Date" format to be consistant with form used in date() function

%sql update SPACEXTBL set "Launch_Date" = substr("Launch_Date", 7, 4) || '-' || substr("Launch_Date", 4,2) || '-' || substr("Launch_Date", 1,2)

 * sqlite:///my_data1.db
999 rows affected.

[]

In [114]:
%sql select date("Launch_Date") as "First successful landing on ground pad"\
    from SPACEXTBL \
    where "Landing_Outcome" == "Success (ground pad)" \
    order by "Launch_Date" asc \
    limit 1;

 * sqlite:///my_data1.db
Done.

[('2015-12-22',)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [115]:
%sql select "Booster_Version" from SPACEXTBL \
    where "Landing_Outcome" = "Success (drone ship)" \
    and "PAYLOAD_MASS__KG_" between 4000 and 6000;

 * sqlite:///my_data1.db
Done.

[('F9 FT B1022',), ('F9 FT B1026',), ('F9 FT  B1021.2',), ('F9 FT  B1031.2',)]

### Task 7




##### List the total number of successful and failure mission outcomes

In [119]:
%sql select "Mission_Outcome", count("Mission_Outcome") as "Successful missions" from SPACEXTBL \
    group by "Mission_Outcome"

 * sqlite:///my_data1.db
Done.

[(None, 0),
 ('Failure (in flight)', 1),
 ('Success', 98),
 ('Success ', 1),
 ('Success (payload status unclear)', 1)]

Again need to do some debugging. One "Success" entry likely has a misplaced space at the end, and I would also like to group all successes together.

In [120]:
# Debugging
# Remove extra space after "Success "

%sql update SPACEXTBL set "Mission_Outcome" = "Success" where "Mission_Outcome" = "Success ";

 * sqlite:///my_data1.db
1 rows affected.

[]

In [173]:
%sql select substr("Mission_Outcome",1,7) as "Mission Outcome", \
    count("Mission_Outcome") as "Count"\
    from SPACEXTBL \
    group by "Mission Outcome" \
    order by "Count" desc \
    limit 2;

 * sqlite:///my_data1.db
Done.

[('Success', 100), ('Failure', 1)]

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [179]:
%sql select "Booster_Version" from SPACEXTBL \
    where "PAYLOAD_MASS__KG_" = (select max("PAYLOAD_MASS__KG_") from SPACEXTBL) \
    order by "Booster_Version";

 * sqlite:///my_data1.db
Done.

[('F9 B5 B1048.4',),
 ('F9 B5 B1048.5',),
 ('F9 B5 B1049.4',),
 ('F9 B5 B1049.5',),
 ('F9 B5 B1049.7 ',),
 ('F9 B5 B1051.3',),
 ('F9 B5 B1051.4',),
 ('F9 B5 B1051.6',),
 ('F9 B5 B1056.4',),
 ('F9 B5 B1058.3 ',),
 ('F9 B5 B1060.2 ',),
 ('F9 B5 B1060.3',)]

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 4, 2) as month to get the months and substr(Date,7,4)='2015' for year.**

In [183]:
%sql select "Launch_Date" from SPACEXTBL

 * sqlite:///my_data1.db
Done.

[('2010-04-06',),
 ('2010-08-12',),
 ('2012-05-22',),
 ('2012-08-10',),
 ('2013-01-03',),
 ('2013-09-29',),
 ('2013-03-12',),
 ('2014-06-01',),
 ('2014-04-18',),
 ('2014-07-14',),
 ('2014-05-08',),
 ('2014-07-09',),
 ('2014-09-21',),
 ('2015-10-01',),
 ('2015-11-02',),
 ('2015-02-03',),
 ('2015-04-14',),
 ('2015-04-27',),
 ('2015-06-28',),
 ('2015-12-22',),
 ('2016-01-17',),
 ('2016-04-03',),
 ('2016-08-04',),
 ('2016-06-05',),
 ('2016-05-27',),
 ('2016-06-15',),
 ('2016-07-18',),
 ('2016-08-14',),
 ('2017-01-14',),
 ('2017-02-19',),
 ('2017-03-16',),
 ('2017-03-30',),
 ('2017-01-05',),
 ('2017-05-15',),
 ('2017-03-06',),
 ('2017-06-23',),
 ('2017-06-25',),
 ('2017-05-07',),
 ('2017-08-14',),
 ('2017-08-24',),
 ('2017-07-09',),
 ('2017-09-10',),
 ('2017-11-10',),
 ('2017-10-30',),
 ('2017-12-15',),
 ('2017-12-23',),
 ('2018-08-01',),
 ('2018-01-31',),
 ('2018-02-22',),
 ('2018-06-03',),
 ('2018-03-30',),
 ('2018-02-04',),
 ('2018-04-18',),
 ('2018-11-05',),
 ('2018-05-22',),
 ('2018-04-06',),
 ('2018-06-29',),
 ('2018-07-22',),
 ('2018-07-25',),
 ('2018-07-08',),
 ('2018-10-09',),
 ('2018-08-10',),
 ('2018-11-15',),
 ('2018-03-12',),
 ('2018-05-12',),
 ('2018-12-23',),
 ('2019-11-01',),
 ('2019-02-22',),
 ('2019-02-03',),
 ('2019-04-05',),
 ('2019-05-24',),
 ('2019-12-06',),
 ('2019-07-25',),
 ('2019-06-08',),
 ('2019-11-11',),
 ('2019-05-12',),
 ('2019-12-17',),
 ('2020-07-01',),
 ('2020-01-19',),
 ('2020-01-29',),
 ('2020-02-17',),
 ('2020-07-03',),
 ('2020-03-18',),
 ('2020-04-22',),
 ('2020-05-30',),
 ('2020-04-06',),
 ('2020-06-13',),
 ('2020-06-30',),
 ('2020-07-20',),
 ('2020-07-08',),
 ('2020-08-18',),
 ('2020-08-30',),
 ('2020-03-09',),
 ('2020-06-10',),
 ('2020-10-18',),
 ('2020-10-24',),
 ('2020-05-11',),
 ('2020-11-16',),
 ('2020-11-21',),
 ('2020-11-25',),
 ('2020-06-12',),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,),
 (None,)]

In [200]:
%sql select substr("Launch_Date",6,2) as "Month", \
    "Booster_Version" as "Booster Version", \
    "Launch_Site" as "Launch Site" \
    from (select * from SPACEXTBL where substr("Launch_Date",1,4)=="2015") \
    where "Landing_Outcome" == "Failure (drone ship)" \
    order by "Month";

 * sqlite:///my_data1.db
Done.

[('04', 'F9 v1.1 B1015', 'CCAFS LC-40'),
 ('10', 'F9 v1.1 B1012', 'CCAFS LC-40')]

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [196]:
%sql select "Landing_Outcome", count("Landing_Outcome") as "Count" \
    from SPACEXTBL \
    where date("Launch_Date") between '2010-06-04' and '2017-03-20' \
    group by "Landing_Outcome" \
    order by "Count" desc;

 * sqlite:///my_data1.db
Done.

[('No attempt', 10),
 ('Success (ground pad)', 5),
 ('Success (drone ship)', 5),
 ('Failure (drone ship)', 5),
 ('Controlled (ocean)', 3),
 ('Uncontrolled (ocean)', 2),
 ('Precluded (drone ship)', 1),
 ('Failure (parachute)', 1)]

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>